[workspace]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
name = "playground"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
hello = "python main.py"

[dependencies]
python = ">=3.14.3,<3.15"
nodejs = ">=25.6.0,<25.7"

[pypi-dependencies]
numpy = ">=2.4.2, <3"
